stages:
  - lint
  - test
  - build
  - deploy

image: node:lts-bullseye-slim

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'push'
      when: always
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: always
    - if: $CI_COMMIT_BRANCH
      when: always

test-server:
  stage: test
  script:
    - npm install && npm run test
  allow_failure: false

lint-server: 
  stage: lint
  script: 
    - npm install && npx eslint
  allow_failure: false

build-frontend:
  stage: build
  rules:
    - if: $CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "deploy"
  before_script:
    - apt-get update && apt-get install -y curl
  script:
    - npm install && npm run build
    - curl -X POST https://api.render.com/deploy/srv-{RENDER_SERVICE}key={RENDER_API_KEY}
  artifacts:
    expire_in: 1 day
    when: on_success
    paths:
      - .next/

deploy:
  stage: deploy
  script:
    - echo "Deployment to Render triggered."