stages:
  - dependencies
  - lint
  - test
  - build
  - release

image: node:lts-bullseye-slim

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - .next/cache/

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'push'
      when: always
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: always
    - if: $CI_COMMIT_BRANCH
      when: always


install-dependencies:
  stage: dependencies
  script:
    - npm install
    - npm ci
  artifacts:
    expire_in: 1 day
    paths:
      - node_modules/
    
test-server:
  stage: test
  dependencies:
    - install-dependencies
  script:
    - npm run test
  allow_failure: false
  
lint-server:
  stage: lint
  dependencies:
    - install-dependencies
  script:
    - npx eslint .
  allow_failure: false

# check-unused-packages:
#   stage: lint
#   dependencies:
#     - install-dependencies
#   script:
#     - npx depcheck || true
#   allow_failure: true

build-frontend:
  stage: build
  dependencies:
    - install-dependencies
  rules:
    - if: $CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "staging" || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main" || $CI_COMMIT_BRANCH == "fix-prod"
  script:
    - npm run build
  artifacts:
    expire_in: 1 day
    paths:
      - .next/

build-app-archive:
  stage: release
  variables:
    RELEASE_FILE: release-$CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA.zip
  dependencies:
    - build-frontend
  rules:
    - if: $CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "staging" || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main" || $CI_COMMIT_BRANCH == "fix-prod"
  before_script:
    - npm prune --production
    - npm dedupe 
    - rm -rf node_modules/.cache .next/cache node_modules/.bin
  script:
    - apt-get update && apt-get install -y zip
    - zip -r $CI_PROJECT_DIR/$RELEASE_FILE .next public package.json package-lock.json next.config.js node_modules server.ts
  artifacts:
    expire_in: 1 day
    paths:
      - $RELEASE_FILE


